[2024-04-20 16:04:42,121] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:05,998] INFO _log() L96    * Detected change in 'C:\\Users\\mtmos\\Desktop\\SEQMOVS\\mvp_api\\schemas\\secao.py', reloading - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:06,102] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:08,070] INFO _log() L96    * Detected change in 'C:\\Users\\mtmos\\Desktop\\SEQMOVS\\mvp_api\\schemas\\secao.py', reloading - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:08,169] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:10,154] INFO _log() L96    * Detected change in 'C:\\Users\\mtmos\\Desktop\\SEQMOVS\\mvp_api\\schemas\\secao.py', reloading - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:10,253] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:12,223] INFO _log() L96    * Detected change in 'C:\\Users\\mtmos\\Desktop\\SEQMOVS\\mvp_api\\schemas\\secao.py', reloading - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:12,327] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:15,320] INFO _log() L96    * Detected change in 'C:\\Users\\mtmos\\Desktop\\SEQMOVS\\mvp_api\\schemas\\secao.py', reloading - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:15,425] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:17,414] INFO _log() L96    * Detected change in 'C:\\Users\\mtmos\\Desktop\\SEQMOVS\\mvp_api\\schemas\\secao.py', reloading - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:05:17,518] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:06:35,997] INFO _log() L96   127.0.0.1 - - [20/Apr/2024 16:06:35] "[35m[1mGET /movimentos HTTP/1.1[0m" 500 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-20 16:06:36,011] ERROR _log() L96   Error on request:
Traceback (most recent call last):
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\flask\cli.py", line 950, in app
    raise err from None
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\flask\cli.py", line 939, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\flask\cli.py", line 341, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\flask\cli.py", line 252, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\flask\cli.py", line 247, in locate_app
    __import__(module_name)
  File "C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\app.py", line 9, in <module>
    from schemas import *
  File "C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\schemas\__init__.py", line 4, in <module>
    from schemas.secao import SecaoSchema, SecaoBuscaSchema, SecaoViewSchema, \
ImportError: cannot import name 'SecaoBuscaSchema' from 'schemas.secao' (C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\schemas\secao.py) - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:05,285] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.104:5000 - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:05,300] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:05,330] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,550] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,561] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,572] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,699] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,702] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,710] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:35,830] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:35] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:38,342] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:38] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:38,400] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:38] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:38,444] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:38] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:38,444] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:38] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:38,656] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:38] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:37:38,665] INFO _log() L96   192.168.0.104 - - [24/Apr/2024 17:37:38] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:38:47,567] INFO _log() L96   127.0.0.1 - - [24/Apr/2024 17:38:47] "GET /movimentos HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:38:47,615] INFO _log() L96   127.0.0.1 - - [24/Apr/2024 17:38:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 17:39:21,764] INFO _log() L96   127.0.0.1 - - [24/Apr/2024 17:39:21] "GET /movimentos HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 19:33:29,667] INFO _log() L96   127.0.0.1 - - [24/Apr/2024 19:33:29] "GET /movimentos HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 19:33:41,521] INFO _log() L96   127.0.0.1 - - [24/Apr/2024 19:33:41] "GET /movimentos HTTP/1.1" 200 - - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-24 22:33:38,839] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.104:5000 - call_trace=C:\Users\mtmos\Desktop\SEQMOVS\mvp_api\env\Lib\site-packages\werkzeug\_internal.py L96  
